to_drop: #Variables To Drop
  Youth_case_identification_code : ['R0000100']
  age_25_assets_round : ['Z9142100']
  Age_30_assets_round : ['Z9122600']
  age_20_assets_round : ['Z9050300'] 
  cohabitating_with_a_specific_partner : ['E7021405', 'E7023608']
  specific_partner_id : ['E7031405', 'E7033608']
  second_partner_lived_with : ['E7041701', 'E7041704']
  Arrest_with_missing_data : ['E8033300', 'E8033900']
  Number_of_times_changes_schools : ['E5230600', 'E5232600']
  months_did_not_attend_school : ['E5241100', 'E5242700']
  Schooling_activity_in_summer : ['E5250400', 'E5252600']
  something_stolen_at_school : ['R0068900', 'R0069200']
  place_you_go_on_regular_basis : ['R0071700', 'R0072600']
  Ice_cream_preferences : ['R0322800', 'R0322900']
  pregnancy_ended_info : ['R0353100', 'R0356200']
  income_if_dont_know_if_received_income : ['R0490000', 'R0490100']
  round_act_score_2007 : ['Z9034200']
  round_sat_verbal_score_2007 : ['Z9034000']
  round_sat_math_score_2007 : ['Z9033800']
  year_pregnancy_ended_non_live_birth : ['U1065800', 'U1067500']

  #pending_variables_to_check: ['R0490000','U0958300']


pure_continuous: # Continuous + DO NOT Find Mode Per Year + Dummies Negative Values and Imputation OR Continuous Bins:
  year_attended_each_grade : ['E5220100', 'E5221200']
  Percent_chance_you_get_drunk_next_year_1997 : ['R0514300']
  Percent_chance_you_get_drunk_next_year_2000 : ['R5155800']
  Percent_chance_you_get_drunk_next_five_years : ['R5156900']
  Financial_assets : ['Z9049700', 'Z9050200']
  Net_worth : ['Z9048900', 'Z9049400']
  Earliest_arrest_date : ['E8033000']
  Total_num_arrests : ['E8033100']
  Earliest_incarceration : ['E8043000', 'E8043100'] 
  Age_incarceration : ['E8043200', 'E8043500']
  Num_days_absent_school : ['R0069300']
  Time_wake_in_morning : ['R0071600']
  Num_weekdays_doing_homework : ['R0073000', 'R0073400']
  Num_weekdays_extra_classes : ['R0074000']
  Time_watching_tv : ['R0074200', 'R0074600']
  Time_reading_for_pleasure : ['R0074800', 'R0075200']
  General_health : ['R0320600']
  Days_doing_something_religious : ['R0323900']
  Pregnancy_details : ['R0351400', 'R0352400']
  Lie_cheat_happy_sad : ['R0356500', 'R0356800']
  Pct_chance_arrested_if_stole_car : ['R0443500', 'R0443800']
  Total_income_past_year : ['R0490200']
  Total_hours_worked : ['Z9068800', 'Z9071700']
  School_suspension : ['E5270500', 'E5272700']
  Scores_ACT : ['Z9034100']
  Scores_SAT_verbal : ['Z9033900']
  scores_SAT_math : ['Z9033700']
  Total_hours_self_employed : ['Z9071800', 'Z9072900']
  Times_injured : ['U1100400']
  Num_hours_injured : ['U1099700' , 'U1099900']
  Pregnancies_ended_in_abortion : ['U1072700','U1073000']
  Age_when_got_pregnant : ['U1072500']
  Assets_first_35 : ['Z9141400', 'Z9141600']
  Assets_second_35 : ['Z9141800', 'Z9142000']
  Assets_first_30 : ['Z9121900', 'Z9122100']
  Assets_second_30 : ['Z9122300', 'Z9122500']



pure_categorical: #Categorical + DO NOT Find Mode Per Year + Dummies:        
  demoted_or_skipped_grade : ['E5210100', 'E5211200']
  demoted_or_skipped_grade_different : ['E5260600', 'E5262700']
  Proxy_for_age_grade_attended : ['E5280200', 'E5282700']
  Lived_with_multiple_partners : ['E7041900', 'E7043300']
  House_type_age_35 : ['Z9141700']
  House_type_age_30 : ['Z9122200']
  House_type_age_20 : ['Z9049500']
  house_type_age_25 : ['Z9049600']
  Missing_rounds_arrest_data : ['E8033200']
  Current_incarceration : ['E8043600']
  Agree_with_statements_about_teachers : ['R0069400', 'R0071300']
  Spend_time_doing_homework : ['R0072900']
  Take_extra_classes : ['R0073500']
  Spend_time_watching_tv : ['R0074100']
  Spend_time_reading_for_pleasure : ['R0074700']
  Currently_pregnant : ['R0351300']
  Receive_income_from_job_last_year : ['R0489900']
  Estimated_income_from_wages_salary_tips : ['R0490300']
  Health_limitations: ['U1100200', 'U1100300']
  general_health : ['U1096500']
  Currently_pregnant_with_your_child : ['U1072600']
  Pregnant : ['U1072300', 'U1072400'] 

categorical_find_mode: #Categorical + Find Mode Per Year + Dummies Per Year:
    school_enrollment_variables : ['E5011701', 'E5012905']
    school_ids_variables : ['E5031701', 'E5032903']
    college_enrollment_variables : ['E5111701', 'E5113608']
    college_degree_and_status : ['E5131702', 'E5133608']
    college_ids_variables : ['E5141702', 'E5143608']
    marital_status : ['E7011401', 'E7013608']
    relationship_with_parent : ['Z9031400', 'Z9031600']
    How_pregnancy_ended : ['U1071200', 'U1072000']



categorical_only_use_2_digits: #Categorical + Only Use First 2 Digits Of Response + Find Mode Per Year + Dummies:
  school_type_variables : ['E5021701', 'E5022903']
  college_type_variables : ['E5121702', 'E5123608']


continuous_find_mode: #Continuous + Find Mode Per Year + Dummies Negative Values and Imputation OR Continuous Bins:
  Num_months_pregnant_next_pregnancy_ended : ['U1070300', 'U1071100']
  Age_when_pregnancy_ended : ['U1069400', 'U1070200']

